# 389. Find the Difference
# Solved
# Easy
# Topics
# premium lock icon
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string 
# s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        a=0
        for ch in s:
            a^=ord(ch)
        for ch in t:
            a^=ord(ch)
        return (chr(a))
    

# Time Complexity = O(n)
# Space Complexity = O(1)



# XOR (^) is used because it has two important properties: a ^ a = 0 and 0 ^ a = a.
# We XOR the ASCII values (ord()) of all characters in both strings. Every character that appears 
# in both s and t cancels out because x ^ x = 0. After all cancellations, 
# only the extra character remains. Finally, chr() converts the remaining ASCII value back to its character.

# s = "abcd"
# t = "abcde"

# 0 ^ a ^ b ^ c ^ d ^ a ^ b ^ c ^ d ^ e
# = 0 ^ e
# = e